#define DEAD_MONTH 0
#define DEAD_YEAR  0
#define DEAD_DAY   0
#define MYSQL_SERVER   "localhost"
#define MYSQL_USER     "root"
#define MYSQL_PASSWD   "cheese"
#define MYSQL_DATABASE "celibero"
#define SERIAL_NUMBER  "1145"
#define CPUID_FAKE "GenuineIntel-00000f27-bfebf9ff"
